// ignore_for_file: constant_identifier_names, dangling_library_doc_comments
/// Flutter icons PDFHawkIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PDFHawkIcons
///      fonts:
///       - asset: fonts/PDFHawkIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class PDFHawkIcons {
  PDFHawkIcons._();

  static const _kFontFam = 'PDFHawkIcons';
  static const String? _kFontPkg = null;

  static const IconData approve = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_document = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData split = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pdf = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData merge = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention_circled = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_empty = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_center = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_justify = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_width = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_height = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_left = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_right = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floppy = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docs = IconData(0xf0c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_bullet = IconData(0xf0ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_numbered = IconData(0xf0cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strike = IconData(0xf0cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underline = IconData(0xf0cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table = IconData(0xf0ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData columns = IconData(0xf0db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paste = IconData(0xf0ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text = IconData(0xf0f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = IconData(0xf114, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open_empty = IconData(0xf115, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crop = IconData(0xf125, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData superscript = IconData(0xf12b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscript = IconData(0xf12c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_inv = IconData(0xf15b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text_inv = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_name_up = IconData(0xf15d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_name_down = IconData(0xf15e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alt_up = IconData(0xf160, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alt_down = IconData(0xf161, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_number_up = IconData(0xf162, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_number_down = IconData(0xf163, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf = IconData(0xf1c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_word = IconData(0xf1c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_excel = IconData(0xf1c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_powerpoint = IconData(0xf1c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_image = IconData(0xf1c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_code = IconData(0xf1c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData header = IconData(0xf1dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paragraph = IconData(0xf1dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders = IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyright = IconData(0xf1f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xf1fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
